name: health1
description: A new Flutter project.Demonstrates how to use the sensors plugin.
publish_to: 'none' 
version: 1.0.0+1

#environment:
#  sdk: ">=2.12.0 <3.0.0"
environment:
    sdk: ">=2.8.0 <3.0.0"

dependencies:
  sqflite: ^1.3.0
  fl_chart: ^0.36.1
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^18.4.49
  direct_select: ^2.0.0
  pedometer:
    git:
      url: git://github.com/feelfreelinux/flutter-plugins.git
      path: packages/pedometer
  shared_preferences: ^0.5.7+3
  google_fonts: ^2.1.0
  jiffy: ^4.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  date_time_picker: ^2.1.0
  provider: ^6.0.1
  sensors:
  charts_flutter: ^0.10.0
  path: ^1.6.2
  just_audio: ^0.9.18
  firebase_core: ^1.10.2
  firebase_database: ^8.2.0
  

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
  http_parser: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: 'assets/logo.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/UserIcon.png
    - assets/age.png
    - assets/gender.png
    - assets/height.png
    - assets/sport.png
    - assets/sleep.png
    - assets/user.png
    - assets/walk.png
    - assets/weight.png
    - assets/logo.jpg
    - assets/muscle.png
    - assets/plant.png
    - assets/angle.png
    - assets/orientation.png
    - assets/acceleration.png
    - assets/gyroscope.png
    - assets/ding.mp3
    - assets/warning.mp3
    - assets/shoulder_flexion_deltoid_test.jpg
    - assets/Biceps_Brachii_Test.jpg
    